version: '3.6'

services:

  mb:
    image: metabase/metabase:v0.30.0
    # image: metabase/metabase:v0.25.2
    ports:
      - "6151:3000"
    volumes:
      - ../data/metabasedata:/metabase-data
    env_file:
      - .env
    # depends_on:
      # - db
    restart: always
    networks:
      - sister
    # https://medium.freecodecamp.org/how-to-setup-log-rotation-for-a-docker-container-a508093912b2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "30"

  # db:
    # image: mysql:5.7
    # restart: always
    # env_file:
      # - .env
    # # ports:
      # # - "6022:3306"
    # volumes:
      # - ../data/metabasedata/mysqldata/:/var/lib/mysql/
    # networks:
      # - sister
 
  # adminer:
    # image: adminer:4.6.3
    # restart: always
    # ports:
      # - 6053:8080
    # networks:
      # - sister
 
networks:
  sister:
    name: sister
      external:true
     